name: Test

on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
        matrix:
          os: [ubuntu-latest]
          arch: [linux/arm64, linux/amd64]
          ver: [v5.2]
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    steps:
        - uses: actions/checkout@v3
          with:
            submodules: true
    
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
    
        - name: Build ${{ matrix.arch }}
          run: |
            docker run --platform ${{ matrix.arch }} --rm integem/notebook:maix_train_mx_${{ matrix.ver }} bash -c '
            python yolov5/train.py --img 224 --epoch 30 --data duck1k_dataset.yaml --weights yolov5s.pt --workers 0
            python yolov5/export.py --weight yolov5/runs/train/exp/weights/best.pt --include onnx --img 224 320
            cp -rf yolov5/runs/train/exp/weights/best.onnx ./best.onnx
            chmod +x ./light/convert_yolov5_to_cvimodel.sh && bash ./light/convert_yolov5_to_cvimodel.sh best "/workspace/datasets/duck1k_yolo/images/val" "/workspace/datasets/duck1k_yolo/images/train/11770_116.jpg"
            cp -rf workspace/best_int8.cvimodel ./best_int8.cvimodel
            exit
            '